FROM nicolasbarbe/magnolia-base
FROM nicolasbarbe/magnolia-base

MAINTAINER Nicolas Barbé "https://github.com/nicolasbarbe"

COPY oneToOne-webapp/target/oneToOne-webapp*.war $CATALINA_BASE/webapps/ROOT.war